name: Bing_Wallpaper

on:
  schedule:
    - cron: "30 16 * * *" # 每天在北京时间0点30分执行
  workflow_dispatch:

jobs:
  play:
    runs-on: ubuntu-latest
    container:
      image: docker://ubuntu:20.04
      options: --env TZ=Asia/Shanghai # 设置容器时区为北京时间
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
      - name: Npm install
        run: npm install
      - name: Run Project
        run: npm run build
      - name: prettier
        run: npm run prettier
      - name: Commit files
        run: |
          git config --local user.email "exposir@foxmail.com"
          git config --local user.name "exposir"
          git pull
          git add ./
          git commit -m "update wallpaper"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.MY_GIT_TOKEN }}
          branch: main
