name: Bing_Wallpaper

on:
  schedule:
    - cron: "1 17 * * *" # 每天北京时间凌晨0点1分执行 (UTC 时间下午 4 点 1 分)
  workflow_dispatch:

jobs:
  play:
    runs-on: ubuntu-latest
    env: # 设置整个 job 的环境变量
      TZ: Asia/Shanghai
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com/
      - name: Npm install
        run: npm install
      - name: Run Project
        run: npm run build
      - name: Commit files
        run: |
          git config --local user.email "exposir@foxmail.com"
          git config --local user.name "exposir"
          git pull
          git add ./
          git commit -m "update wallpaper"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.MY_GIT_TOKEN }}
          branch: main
