name: Bing_Wallpaper_Node

on:
  schedule:
    - cron: "10 1,12,23 * * *"
  workflow_dispatch:

jobs:
  play:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
      - name: build
        run: npm install
      - name: Run Project
        run: node index.js
      - name: Commit files
        run: |
          git config --local user.email "897205285@@@.com"
          git config --local user.name "exposir"
          git pull
          git add static/*
          git commit -m "update"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.MY_GIT_TOKEN }}
          branch: main
