name: Update Bing Wallpaper

on:
  schedule:
    - cron: "1 17 * * *" # Run daily at 1:01 AM Beijing Time (4:01 PM UTC)
  workflow_dispatch:

jobs:
  update_wallpaper:
    runs-on: ubuntu-latest
    env: # Set environment variables for the entire job
      TZ: Asia/Shanghai
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: npm run build
      - name: Configure Git user
        run: |
          git config --local user.email "exposir@foxmail.com"
          git config --local user.name "exposir"
          git add ./
          git commit -m "Update wallpaper on $(date '+%Y-%m-%d %H:%M:%S %Z')"
      - name: Push changes to the repository
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.MY_GIT_TOKEN }}
          branch: main
