name: Bing_Wallpaper_node

on:
  push:
    branches:
      - main
  schedule:
    - cron: "10 1,2,3,4,5,17 * * *"

  workflow_dispatch:

jobs:
  play:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
      - name: Run Project
        run: node index.js
